### ISSUE TITLE
Invoice exporting adds view | edit to fields

### ISSUE THREAD

**Issue by rossjcooper** [TTFerreira/ivd-assets#6]
I'm guesing your are converting your HTML table in .csv/.xls format but it is adding the edit and view link text into the fields.
[IVD Assets - Invoices (1).xlsx](https://github.com/TTFerreira/ivd-assets/files/381407/IVD.Assets.-.Invoices.1.xlsx)

I found this to be a great package to help with exporting eloquent models: https://github.com/Maatwebsite/Laravel-Excel

**Comment by TTFerreira** [comment]
I am using the DataTables 'Buttons' extension to export to Excel, .CSV and HTML Copy.
I excluded the 'Actions' column from all three exports now.

Thanks for reporting all these issues. Please keep them coming.

**Comment by rossjcooper** [comment]
No problem glad to help a fellow laravel dev
